name: weather
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  dio: any
  flutter_native_splash: ^1.3.1
  geolocator: ^7.7.1
  retrofit: any
  logger: any
  json_annotation: 4.3.0
  shared_preferences: ^2.0.8
  flutter_svg: ^0.23.0+1
  flutter_local_notifications: ^9.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: any
  retrofit_generator: any
  build_runner: any
flutter:
  uses-material-design: true


  assets:
    - images/


  fonts:
    - family: font
      fonts:
        - asset: fonts/roya.ttf
